dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
- oraclejdk9
- openjdk8
branches:
  only:
  - master
  - release
cache:
  directories:
  - "$HOME/.m2"
notifications:
  slack:
    secure: oeFWJcDGyWC+uSXJQfH++ulgqpeBKtF8s5ljf8EbJJQMNYl19ofTC/7gX3V0SzRSQ/ky76ZYSCou/LP7W3Tek1qJgb92pgafXSaj/SxnSbL0mIlI1FXiArADCFHfkFcZ1/RJsbk6TJEyTLAYmaSGW5uqLLD27Hy8oGxNYfaN9Hxg6j6tcHH+9KQlvqjzM8NLpwo18TxpgpqtglGoauF7RxoA0bTbtswUEFHW1taow4c87/ciLLFIXsxeVTSWQ5gH4wNTIEfJkyBMQ2VvnV3k5GSjljZTQm+E+kcr3jq+lQP+WE74T5BvkkHiKr8R6DCqtNsNyNlu2fVFN9UbowvSTt0bjj4ykPhq982ftSFpmOPNv1D02KuYSnhzKa6fVMM0C0Y9rLpjMuuSBJOHlDdl+80O6IcSU0fbo4U5D5HMaBJA1dtOWMVNvUg7J2eLgGuNyYPh8VXieOiyRNTz7DvHXKs6EalRbOYsZA5Y8a0jldwhcdYuKSHQy7lM3KFSj3A8T0MDigu2rWJ/AF/MvblFbMT5MI9PNhTWrFCiiill4DOiL7k5NFsnzeM7gjgCwjxvw7ilECcr0hGXMa6hXtLk3LBO77byr1exTWw47omoKNStePGX6zvYz9TlQmmLQTxMYtOTBXukVRWmxvoqrRve2bAuDV8wOWmFrIPBRSSEuBM=
    on_success: change
    on_failure: always
