# paths can be set here, by environment variable or java property.
systems: [ edu.umn.biomedicus.BiomedicusSystem ]
paths:
  #home: /absolute-path
  #data: /absolute-path
  #settings ending in path will be loaded as Path, if not absolute they will be resolved against the data directory
settings:
  acronym:
    checkParseTokens: yes
    labelOtherSenses: yes
    useAlignment: no
    expansionsModel: acronym/expansions.txt
    alignmentModel: acronym-alignment/alignment.yml
    model: vector
    cutoffScore: 0.001
    vector:
      model: acronym/vectorSpace.yml
      trainer:
        expansionMap: REPLACE_ME_PATH_TO
        uniqueIdMap: REPLACE_ME_PATH_TO
        longforms: REPLACE_ME_PATH_TO
        outputDir: REPLACE_ME_PATH_TO
    senseMap:
      senseVectors: acronym/senseVectors
      inMemory: no
    orthographicModel: acronym-orthographic/orthographicModel.yml
  concepts:
    db: concepts
    inMemory: no
    filters:
      sui: conceptFilters/filteredSuis.txt
      suicui: conceptFilters/filteredSuiCuis.txt
      cui: conceptFilters/filteredCuis.txt
      tui: conceptFilters/filteredTuis.txt
  family:
    relatives: family/relatives.txt
  measures:
    numbers:
      nrnum: measures/NRNUM
      nrvar: measures/NRVAR
      includeFractions: yes
      includePercent: no
    units:
      model: measures/concepts.tsv
    indefiniteQuantifiers:
      left: measures/leftIndefiniteQuantifiers.txt
      right: measures/rightIndefiniteQuantifiers.txt
      local: measures/localIndefiniteQuantifiers.txt
      fuzzy: measures/fuzzyValues.txt
    standaloneQuantifiers: measures/standaloneQuantifiers.txt
    timeUnits: measures/timeUnits.txt
    timeFrequencyUnits: measures/timeFrequencyUnits.txt
  modification:
    history: modification/history.yml
    negation: modification/negation.yml
    probability: modification/probability.yml
  normalization:
    db: normalization
    inMemory: no
  opennlp:
    sentence:
      model: opennlp/sentence.bin
  parser.implementation: opennlp
  python:
    executable: python3
    home: python
    data:
    server:
      launch: yes
      host: localhost
      port: 8888
    sentences:
      vocab: sentences/vocab
      wordsModel: mimic.100.vec
      config: sentences/hparams.yml
      weights: sentences/weights.hdf5
  time:
    days: time/days.txt
    months: time/months.txt
    timesOfDay: time/timesOfDay.txt
    seasons: time/seasons.txt
  tnt:
    trigram: tnt/trigram.yml
    word:
      inMemory: no
      db: tnt/words
      metadata: tnt/wordMetadata.yml
    beam.threshold: 2.0
  sections.headers: sections/headers.txt
  semanticNetwork:
    srdef: semnetwork/SRDEF
    semgroups: semnetwork/SemGroups.txt
  sh:
    usageFrequencyPhrases: sh/usageFrequencyPhrases.txt
    usageFrequencyPatterns: sh/usageFrequencyPatterns.txt
    statusPhrases: sh/genericStatusPhrases.txt
    genericMethodPhrases: sh/genericMethodPhrases.txt
    alcohol:
      amountExpr: sh/alcohol/amountSearchExpr.txt
      amountUnits: sh/alcohol/amountUnits.txt
      candidateCues: sh/alcohol/candidateCues.txt
      cueIgnore: sh/alcohol/alcoholIgnore.txt
      methodPhrases: sh/alcohol/methodPhrases.txt
      nonalcoholicDrinks: sh/alcohol/nonalcoholicDrinks.txt
      statusPhrases: sh/alcohol/statusPhrases.txt
      types: sh/alcohol/types.txt
    drugs:
      amountExpr: sh/drugs/amountSearchExpr.txt
      amountUnits: sh/drugs/amountUnits.txt
      candidateCues: sh/drugs/candidateCues.txt
      methodPhrases: sh/drugs/methodPhrases.txt
      types: sh/drugs/types.txt
    nicotine:
      amountExpr: sh/nicotine/amountSearchExpr.txt
      amountUnits: sh/nicotine/amountUnits.txt
      candidateCues: sh/nicotine/candidateCues.txt
      methodPhrases: sh/nicotine/methodPhrases.txt
      statusPhrases: sh/nicotine/statusPhrases.txt
      types: sh/nicotine/types.txt
  specialist: SPECIALIST/LEX
  spelling:
    arpa: spell/UPMC.arpa
    maxEditDistance: 4
  stopwords:
    model: fileBased
    fileBased: stopwords/PubMedStopwords.txt
  syntaxnet:
    installationDir: REPLACE_ME_PATH_TO_/GoogleParser/models/syntaxnet
    modelDir: syntaxnet/models/parsey_mcparseface
  vocabulary:
    db: vocabulary
    inMemory: no
